PeOp/src/java/peop/infraestructure/models/categoriasTemasModel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peop.infraestructure.models;

/**
 *
 * @author alquimista
 */
public class categoriasTemasModel {

    private String IdCategoria;
    private String NombreCategoria;
    private String NombreSubCategoria;

    public categoriasTemasModel() {
    }

    public categoriasTemasModel(String IdCategoria, String NombreCategoria, String NombreSubCategoria) {
        this.IdCategoria = IdCategoria;
        this.NombreCategoria = NombreCategoria;
        this.NombreSubCategoria = NombreSubCategoria;
    }

   

    public String getIdCategoria() {
        return IdCategoria;
    }

    public void setIdCategoria(String IdCategoria) {
        this.IdCategoria = IdCategoria;
    }

    public String getNombreCategoria() {
        return NombreCategoria;
    }

    public void setNombreCategoria(String NombreCategoria) {
        this.NombreCategoria = NombreCategoria;
    }

    public String getNombreSubCategoria() {
        return NombreSubCategoria;
    }

    public void setNombreSubCategoria(String NombreSubCategoria) {
        this.NombreSubCategoria = NombreSubCategoria;
    }

}

PeOp/src/java/peop/infraestructure/models/opinionModel.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peop.infraestructure.models;

import peop.core.validations.OpinionValidation;

/**
 *
 * @author alquimista
 */
public class opinionModel {

    private String tema;
    @OpinionValidation
    private String valoracion;
    private String opinionGeneral;
    private String vom;
    private String IdCategoria;
    private String IdSubCategoria;
    private String IdTema;
    private String IdUsuario;
     private String IdOpinion;
     private String dbTimeStamp;

    public opinionModel() {
    }

    public opinionModel(String tema, String valoracion, String opinionGeneral, String vom, String IdCategoria, String IdSubCategoria, String IdTema, String IdUsuario, String IdOpinion, String dbTimeStamp) {
        this.tema = tema;
        this.valoracion = valoracion;
        this.opinionGeneral = opinionGeneral;
        this.vom = vom;
        this.IdCategoria = IdCategoria;
        this.IdSubCategoria = IdSubCategoria;
        this.IdTema = IdTema;
        this.IdUsuario = IdUsuario;
        this.IdOpinion = IdOpinion;
        this.dbTimeStamp = dbTimeStamp;
    }

    

    

    public String getTema() {
        return tema;
    }

    public void setTema(String tema) {
        this.tema = tema;
    }

    public String getValoracion() {
        return valoracion;
    }

    public void setValoracion(String valoracion) {
        this.valoracion = valoracion;
    }

    public String getOpinionGeneral() {
        return opinionGeneral;
    }

    public void setOpinionGeneral(String opinionGeneral) {
        this.opinionGeneral = opinionGeneral;
    }

    public String getVom() {
        return vom;
    }

    public void setVom(String vom) {
        this.vom = vom;
    }

    public String getIdCategoria() {
        return IdCategoria;
    }

    public void setIdCategoria(String IdCategoria) {
        this.IdCategoria = IdCategoria;
    }

    public String getIdSubCategoria() {
        return IdSubCategoria;
    }

    public void setIdSubCategoria(String IdSubCategoria) {
        this.IdSubCategoria = IdSubCategoria;
    }

    public String getIdTema() {
        return IdTema;
    }

    public void setIdTema(String IdTema) {
        this.IdTema = IdTema;
    }

    public String getIdUsuario() {
        return IdUsuario;
    }

    public void setIdUsuario(String IdUsuario) {
        this.IdUsuario = IdUsuario;
    }

    public String getIdOpinion() {
        return IdOpinion;
    }

    public void setIdOpinion(String IdOpinion) {
        this.IdOpinion = IdOpinion;
    }

    public String getDbTimeStamp() {
        return dbTimeStamp;
    }

    public void setDbTimeStamp(String dbTimeStamp) {
        this.dbTimeStamp = dbTimeStamp;
    }
    

}

PeOp/web/WEB-INF/Views/Tools/ListView.jsp
<%@page import="java.util.List"%>
<%@page import="peop.libs.poolconnection.dao.opinion"%>

<div id="divFiltroOpiniones">
    <table  class="table table-striped" id="tablaFiltroOpiniones">
        <thead >
            <tr>
                <th scope="col">#</th>
                <th scope="col">Id Tema</th>
                <th scope="col">Opinion General</th>
                <th scope="col">Verdad o Mentira </th>
                <th scope="col">Id Usuario</th>
                <th scope="col">Apellidos</th>
                <th scope="col">Nacionalidad</th>
                <th scope="col">Pais Origen</th>
                <th scope="col">Pais Residencia</th>
                <th scope="col">Fecha Nacimiento</th>
                <th scope="col">Sexo</th>
                <th scope="col">Reacciones</th>
            </tr>
        </thead>

        <tbody>
          <!--  se completa por Ajax -->
        </tbody>

    </table>
</div>

PeOp/web/WEB-INF/Views/Tools/Opinar.jsp
<%-- 
    Document   : Opinar
    Created on : 13 dic. 2020, 19:05:22
    Author     : alquimista
--%>

<%@page import="java.util.ArrayList"%>
<%@page import="java.util.List"%>
<%@page import="peop.infraestructure.models.options_OpinionGeneralModel"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>  
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Opinar - PeOp</title>
        <%@include file='../Shared/styles.jsp'%>

    </head>
    <body style="background-image:url(${pageContext.request.contextPath}/resources/images/shared/cutcube.png)">
        <%@include file='../Shared/MenuPrincipal.jsp'%>

        <form:form action="procesarOpinion" modelAttribute="opinion">
            <div class="container-fluid">
                <h4 class="text-left mt-3">Dar mi opinion sobre ${categoriaTemaEscogido.nombreTema}</h4>
                <hr/>

                <div class="row justify-content-center ">
                    <div class="col-md-2 pl-0 ml-5 mt-3 text-right">
                        <label for="nombreCategoria">Categoria seleccionada:</label>
                    </div>
                    <div class="col-md-4 mt-2 pl-0">
                        <input class="form-control text-secondary" type="text" id="nombreCategoria" placeholder="${categoriaTemaEscogido.nombreCategoria}"   readonly> 
                        <form:input path="IdCategoria" cssClass="form-control d-none" type="text" id="IdCategoria" value="${categoriaTemaEscogido.idCategoria}" />
                    </div>
                </div>   
                <div class="row justify-content-center">
                    <div class="col-md-2 pl-0 ml-5 mt-3 text-right">
                        <label for="subcategoria">SubCategoria seleccionada:</label>
                    </div>
                    <div class="col-md-4 mt-2 pl-0">
                        <input class="form-control text-secondary" type="text" id="subcategoria" placeholder="${categoriaTemaEscogido.nombreSubCategoria}"  readonly>  
                        <form:input path="IdSubCategoria" cssClass="form-control d-none" type="text" id="IdSubCategoria" value="${categoriaTemaEscogido.idSubCategoria}" />
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-2 pl-0 ml-5 mt-3 text-right">
                        <label for="tema">Tema seleccionado:</label>
                    </div>
                    <div class="col-md-4 mt-2 pl-0">
                        <input class="form-control text-secondary" type="text" id="tema" placeholder="${categoriaTemaEscogido.nombreTema}" readonly>  
                        <form:input path="IdTema" cssClass="form-control d-none" type="text" id="IdSubCategoria" value="${categoriaTemaEscogido.idTema}" />
                    </div>
                </div>

                <div class="row justify-content-center mt-3">
                    <div class="col-md-6">
                        <label class="text-info border-bottom mb-2">
                            Opinion general: 
                        </label>

                        <div class="form-check mb-2">
                            <%   
                            List<options_OpinionGeneralModel> lstOptions =  new ArrayList<>();
                            lstOptions = (List<options_OpinionGeneralModel>) request.getAttribute("lstOpciones");
                            for(options_OpinionGeneralModel option :lstOptions) {
                                String op = option.getOpcion();
                            %>
                            <div class="col-md-4">
                                <form:radiobutton cssClass="form-check-input" path="opinionGeneral" label="<%=op%>" value="<%=op%>"/>
                            </div>
                            <%}%>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <label class="text-info border-bottom mb-2">
                            Crees que es verdad o mentira:
                        </label> <br/>
                        <div class="form-check mb-2">
                            <div class="col-md-3">
                                <form:radiobutton cssClass="form-check-input" path="vom" label="Mentira" value="Mentira"/> 
                            </div>
                            <div class="col-md-3">
                                <form:radiobutton cssClass="form-check-input" path="vom" label="Verdad" value="Verdad"/>
                            </div>
                        </div>
                        Valoracion: <form:input cssClass="form-control" path="valoracion"/> <form:errors path="valoracion" style="color:red"/><br/> 
                    </div>
                </div>
                <div class="row justify-content-center text-center">
                    <div class="col-md-6">
                        <input type="submit" class="btn btn-outline-success" value="Enviar Opinion">
                        <a class="btn btn-outline-info" role="button" href="TemasOpinion">Atras</a>
                    </div>
                </div>
            </div>

            <!-- 
                 Valoracion: <form:input path="valoracion"/> <br/>
                 Valoracion: <form:input path="valoracion"/> <br/>
                 Valoracion: <form:input path="valoracion"/> <br/> 
                 Valoracion: <form:input path="valoracion"/> <br/> 
            -->

        </form:form>

        <%@include file='../Shared/footer.jsp' %>

PeOp/web/WEB-INF/Views/Tools/opinionRegistrada.jsp
<%-- 
    Document   : opinionRegistrada
    Created on : 13 dic. 2020, 21:55:20
    Author     : alquimista
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Opinion Registrada</title>
        <%@include file='../Shared/styles.jsp'%>
   
    </head>
    <body style="background-image:url(${pageContext.request.contextPath}/resources/images/shared/cutcube.png)">
        <%@include file='../Shared/MenuPrincipal.jsp' %>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <br/>
                    <h4 style="text-align: left">Opinion registrada con exito</h4>
                    <hr/>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <p style="text-align: center">Tu valoracion ha sido <strong>${opinion.valoracion}</strong></p>
                    <p style="text-align: center">Tu valoracion ha sido <strong>${opinion.vom}</strong></p>
                </div>
            </div>

            <br/>
            <div class="row justify-content-center">
                <div class="col-6">
                    <!--* Card init *-->
                    <div class="card">
                        <!-- Card header -->
                        <div class="card-header">
                            <!-- Title -->
                            <h5 class="h5 mb-0">Otras opiniones sobre este tema</h5>
                        </div>
                        <!-- Card body -->
                        <div class="card-body">
                            <div class="chart">
                                <!-- Chart wrapper -->
                                <canvas id="myChart" class="chart-canvas"></canvas>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-6">
                    <!--* Card init *-->
                    <div class="card">
                        <!-- Card header -->
                        <div class="card-header">
                            <!-- Title -->
                            <h5 class="h5 mb-0">Cantidad de opiniones sobre este tema</h5>
                        </div>
                        <!-- Card body -->
                        <div class="card-body">
                            <div class="chart">
                                <!-- Chart wrapper -->
                                <canvas id="myChart2" class="chart-canvas"></canvas>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="row justify-content-center mt-3">
                <div class="col-12">
                    <div class="text-center">
                        <a class="btn btn-outline-primary" role="button" href="TemasOpinion"> Volver a Opinar</a>
                        <a class="btn btn-outline-primary" role="button" href="../Profile/verPerfil"> Ver Perfil</a>
                        <a class="btn btn-outline-primary" role="button" href="verOpiniones"> Ver Opiniones</a>
                        <a class="btn btn-outline-primary" role="button" href="../Index"> Ir al Inicio</a>
                    </div>
                </div>
            </div>
        </div>
                

    
        <%@include file='../Shared/footer.jsp' %>

PeOp/web/WEB-INF/Views/Tools/particlesView.jsp
<canvas id="c"></canvas>

PeOp/web/WEB-INF/Views/Tools/verOpiniones.jsp
<%-- 
    Document   : verOpiniones
    Created on : 27 dic. 2020, 16:02:12
    Author     : alquimista
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>  
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- <meta http-equiv="refresh"  content="5" /> -->
        <title>Ver Opiniones - PeOp</title>
        <%@include file='../Shared/styles.jsp' %>


    </head>

    <body style="background-image:url(${pageContext.request.contextPath}/resources/images/shared/cutcube.png)">
        <!-- Menu Principal superior -->
        <%@include file='../Shared/MenuPrincipal.jsp' %>
        <!-- Menu Principal superior -->

        <div class="container-fluid">

            <div class="row">
                <div class="col col-12 mt-2">
                    <h4>Ver Opiniones</h4>
                    <hr/>
                </div>
            </div>
            <div class="row">
                <div class="col col-sm-3">
                    <label>Residentes en:</label>
                    <select  class="form-select" id="filtro_paisResidencia">
                        <%
                        List<String> lstPaies2 = (List<String>) request.getAttribute("lstP");
                        String p= "";
                            for(String pa:lstPaies2) {
                                p = pa;
                        %>
                        <option value="<%=p%>" label="<%=p%>"></option>
                        <%}%>
                    </select>
                </div>
                <div class="col col-sm-3">
                    <label>Nacidos en:</label>
                    <select  class="form-select" id="filtro_paisOrigen">
                        <%
                        List<String> lstPaies3 = (List<String>) request.getAttribute("lstPaises2");
                        String p3= "";
                            for(String pais3:lstPaies3) {
                                p3 = pais3;
                        %>
                        <option value="<%=p3%>" label="<%=p3%>"></option>
                        <%}%>
                    </select>
                </div>
                <div class="col col-sm-3">
                    <label>Edad:</label>
                    <input class="form-control" type="date" id="filtro_fechaN" name="datetime1"/>                                   
                </div>

                <div class="col col-sm-3">
                    <label>Sexo:</label>
                    <select  class="form-select" id="filtro_sexo">

                        <option value="Hombre" label="Hombre"></option>
                        <option value="Mujer" label="Mujer"></option>
                        <option value="Alternativo" label="Alternativo"></option>

                    </select>
                </div>
            </div>

            <div class="row justify-content-center mt-3">
                <div class="col col-12 text-center">
                    <button class="btn btn-outline-success" onclick="verOpiniones()"><i class="fas fa-search mr-1"></i>Ver Opinines</button>
                    
                </div>
            </div>

        </div>


        <hr/>
        <div class="container-fluid">
            <div class ="row">

                <nav class="nav fill justify-content-center">
                    <div class="nav nav-tabs " id="nav-tab" role="tablist">
                        
                        <a class="nav-link active" id="nav-list-tab" data-bs-toggle="tab" href="#nav-list" role="tab" aria-controls="nav-list" aria-selected="true">
                            <i class="fas fa-list mr-2"></i>
                            Lista 
                        </a> 
                        
                        <a class="nav-link" id="nav-panel-tab" data-bs-toggle="tab" href="#nav-panel" role="tab" aria-controls="nav-panel" aria-selected="false">
                            <i class="fas fa-th mr-2"></i>
                            Panel 
                        </a> 
                        
                        <a class="nav-link" id="nav-particulas-tab" data-bs-toggle="tab" href="#nav-particulas" role="tab" aria-controls="nav-particulas" aria-selected="false">
                            <i class="fas fa-braille mr-2"></i>
                            Particulas
                        </a>

                    </div>
                </nav>
            </div>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-list" role="tabpanel" aria-labelledby="nav-list-tab">  <%@include file='ListView.jsp'%></div> 
                <div class="tab-pane fade" id="nav-panel" role="tabpanel" aria-labelledby="nav-panel-tab">  <%@include file='panelView.jsp'%></div>
                <div class="tab-pane fade" id="nav-particulas" role="tabpanel" aria-labelledby="nav-particulas-tab">  <%@include file='particlesView.jsp'%></div> 

            </div>
        </div>

        <%@ include file='../Shared/footer.jsp' %>